### ISSUE TITLE
Corner error

### ISSUE THREAD

**Issue by NES8** [tiny2n/CropperView#1]
![la foto](https://cloud.githubusercontent.com/assets/7712468/3841861/e3a61530-1e31-11e4-8702-81a0d8991071.PNG)

Hi!

There is some problem with the corners.

Good job!

**Comment by tiny2n** [comment]
thank your answer. how was happend ?
i will fix problem that you teach to me.

2014년 8월 7일 목요일, NES8notifications@github.com님이 작성한 메시지:

**Comment by AlexanderZubkov** [comment]
I have the same problem. Have you solved it?

**Comment by AlexanderZubkov** [comment]
I've solved it. Please check my fork.

**Comment by tiny2n** [comment]
thank you for your answer. and solved that. i will check your fork.

나의 iPhone에서 보냄
1. 3. 16. 오전 8:05 AlexanderZubkov notifications@github.com 작성:

**Comment by AlexanderZubkov** [comment]
Thank you for CropperView!
